# Generated by Django 5.1 on 2024-09-16 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountsTrial', '0002_alter_commonuser_house_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonuser',
            name='house_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users_flat', to='accountsTrial.apartment_numbers'),
        ),
    ]
