# Generated by Django 5.1 on 2024-09-16 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountsTrial', '0004_security'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyHelp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('job', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=15)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_help_added', to=settings.AUTH_USER_MODEL)),
                ('apartment', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='daily_help_working', to='accountsTrial.apartment_numbers')),
            ],
        ),
    ]
