# Generated by Django 5.1 on 2024-09-19 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountsTrial', '0005_dailyhelp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(max_length=20)),
                ('license_plate', models.CharField(max_length=20, unique=True)),
                ('house_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vechicles', to='accountsTrial.apartment')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
