# Generated by Django 5.1 on 2024-09-19 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountsTrial', '0006_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='house_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vechicles', to='accountsTrial.apartment_numbers'),
        ),
    ]
